# theme.toml template for a Hugo theme

name = "Death by Numbers"
license = "MIT"
licenselink = "https://github.com/chnm/bom/blob/master/LICENSE"
description = "Theme for the Death by Numbers project at the Roy Rosenzweig Center for History and New Media"
homepage = "http://deathbynumbers.org/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Roy Rosenzweig Center for History and New Media"
  homepage = "https://rrchnm.org"